name: gpa_calculator
description: A Flutter application to calculate GPA.
publish_to: 'none' # This prevents accidental publishing to pub.dev.

# Specify the Flutter and Dart SDK versions
environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  # Add any additional dependencies if needed
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter rules for best practices
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
